pkg:
	(cd .. && zip -r lightspeed.zip lightspeed -x \*~ -x \*.o -x \*.obj -x \*.dll -x \*.exe -x \*.mexglx \*.mexw32 \*.manifest -x \*CVS\* -x \*xrepmat.m)

clean:
	rm *~ */*~ *.dll *.exe *.obj *.o *.mexglx
